export const FEATURES = {
  buildings: {
    title: 'Building Portfolio',
    icon: '🏢',
    description: 'Manage commercial buildings and track energy capacity across your entire portfolio',
    apiPath: 'buildings',
    badge: 'core',
    columns: [
      { key: 'name', label: 'Building Name' },
      { key: 'building_type', label: 'Type' },
      { key: 'total_capacity_kw', label: 'Total kW', format: 'number' },
      { key: 'utilized_capacity_kw', label: 'Used kW', format: 'number' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'name', label: 'Building Name', type: 'text', required: true },
      { key: 'address', label: 'Address', type: 'text' },
      { key: 'building_type', label: 'Building Type', type: 'select', options: ['Office', 'Retail', 'Industrial', 'Healthcare', 'Education', 'Hospitality', 'Data Center', 'Warehouse', 'Government', 'Residential', 'Co-working', 'Manufacturing', 'Mixed Use', 'Transportation', 'Technology'] },
      { key: 'total_capacity_kw', label: 'Total Capacity (kW)', type: 'number' },
      { key: 'utilized_capacity_kw', label: 'Utilized Capacity (kW)', type: 'number' },
      { key: 'floors', label: 'Floors', type: 'number' },
      { key: 'square_footage', label: 'Square Footage', type: 'number' },
      { key: 'year_built', label: 'Year Built', type: 'number' },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'contact_email', label: 'Contact Email', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'maintenance'] },
    ],
    detailFields: [
      { key: 'name', label: 'Building Name' },
      { key: 'address', label: 'Address', fullWidth: true },
      { key: 'building_type', label: 'Type' },
      { key: 'total_capacity_kw', label: 'Total Capacity (kW)' },
      { key: 'utilized_capacity_kw', label: 'Utilized (kW)' },
      { key: 'floors', label: 'Floors' },
      { key: 'square_footage', label: 'Square Footage' },
      { key: 'year_built', label: 'Year Built' },
      { key: 'owner', label: 'Owner' },
      { key: 'contact_email', label: 'Contact Email' },
      { key: 'status', label: 'Status' },
    ],
  },

  'energy-audits': {
    title: 'Energy Audits',
    icon: '🔍',
    description: 'Comprehensive energy audits identifying waste and optimization opportunities in buildings',
    apiPath: 'energy-audits',
    badge: 'core',
    columns: [
      { key: 'building_name', label: 'Building' },
      { key: 'auditor', label: 'Auditor' },
      { key: 'energy_rating', label: 'Rating' },
      { key: 'waste_percentage', label: 'Waste %', format: 'percent' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'building_name', label: 'Building Name', type: 'text', required: true },
      { key: 'auditor', label: 'Auditor', type: 'text' },
      { key: 'audit_date', label: 'Audit Date', type: 'date' },
      { key: 'energy_rating', label: 'Energy Rating', type: 'select', options: ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'F'] },
      { key: 'total_consumption_kwh', label: 'Total Consumption (kWh)', type: 'number' },
      { key: 'waste_percentage', label: 'Waste Percentage', type: 'number' },
      { key: 'recommendations', label: 'Recommendations', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: [
      { key: 'building_name', label: 'Building' },
      { key: 'auditor', label: 'Auditor' },
      { key: 'audit_date', label: 'Audit Date' },
      { key: 'energy_rating', label: 'Energy Rating' },
      { key: 'total_consumption_kwh', label: 'Consumption (kWh)' },
      { key: 'waste_percentage', label: 'Waste %' },
      { key: 'recommendations', label: 'Recommendations', fullWidth: true },
      { key: 'status', label: 'Status' },
    ],
  },

  'capacity-detection': {
    title: 'Capacity Detection',
    icon: '🎯',
    description: 'AI-powered detection of underutilized energy capacity across commercial buildings',
    apiPath: 'capacity-detection',
    badge: 'ai',
    columns: [
      { key: 'building_name', label: 'Building' },
      { key: 'capacity_type', label: 'Type' },
      { key: 'available_capacity_kw', label: 'Available kW', format: 'number' },
      { key: 'confidence_score', label: 'Confidence', format: 'percent' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'building_name', label: 'Building Name', type: 'text', required: true },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'capacity_type', label: 'Capacity Type', type: 'select', options: ['HVAC Overcapacity', 'Lighting Surplus', 'Motor Load Gap', 'Warehouse Idle Capacity', 'HVAC Off-Peak Surplus', 'Conference Room Idle', 'Tenant Vacancy Gap', 'Co-working Off-Hours', 'Server Decommission Gap', 'Common Area Surplus', 'Weekend Idle Capacity', 'Lab Off-Season Gap', 'Cooling Overcapacity', 'Off-Peak Transit Gap', 'Shift Gap Capacity', 'Weekend Demand Drop'] },
      { key: 'total_capacity_kw', label: 'Total Capacity (kW)', type: 'number' },
      { key: 'used_capacity_kw', label: 'Used Capacity (kW)', type: 'number' },
      { key: 'available_capacity_kw', label: 'Available Capacity (kW)', type: 'number' },
      { key: 'detection_method', label: 'Detection Method', type: 'text' },
      { key: 'confidence_score', label: 'Confidence Score (%)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['detected', 'verified', 'utilized', 'dismissed'] },
    ],
    detailFields: [
      { key: 'building_name', label: 'Building' },
      { key: 'location', label: 'Location' },
      { key: 'capacity_type', label: 'Type' },
      { key: 'total_capacity_kw', label: 'Total (kW)' },
      { key: 'used_capacity_kw', label: 'Used (kW)' },
      { key: 'available_capacity_kw', label: 'Available (kW)' },
      { key: 'detection_method', label: 'Method' },
      { key: 'confidence_score', label: 'Confidence %' },
      { key: 'status', label: 'Status' },
    ],
  },

  'community-needs': {
    title: 'Community Needs',
    icon: '🏘️',
    description: 'Assess and prioritize energy needs of underserved communities for equitable distribution',
    apiPath: 'community-needs',
    badge: 'core',
    columns: [
      { key: 'community_name', label: 'Community' },
      { key: 'population', label: 'Population', format: 'number' },
      { key: 'energy_burden_pct', label: 'Energy Burden', format: 'percent' },
      { key: 'priority', label: 'Priority' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'community_name', label: 'Community Name', type: 'text', required: true },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'population', label: 'Population', type: 'number' },
      { key: 'median_income', label: 'Median Income ($)', type: 'number' },
      { key: 'energy_burden_pct', label: 'Energy Burden (%)', type: 'number' },
      { key: 'current_provider', label: 'Current Provider', type: 'text' },
      { key: 'needs_description', label: 'Needs Description', type: 'textarea' },
      { key: 'priority', label: 'Priority (1-5)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['assessed', 'in_progress', 'critical', 'resolved'] },
    ],
    detailFields: [
      { key: 'community_name', label: 'Community' },
      { key: 'location', label: 'Location' },
      { key: 'population', label: 'Population' },
      { key: 'median_income', label: 'Median Income' },
      { key: 'energy_burden_pct', label: 'Energy Burden %' },
      { key: 'current_provider', label: 'Provider' },
      { key: 'needs_description', label: 'Description', fullWidth: true },
      { key: 'priority', label: 'Priority' },
      { key: 'status', label: 'Status' },
    ],
  },

  aggregation: {
    title: 'Energy Aggregation',
    icon: '🔗',
    description: 'Aggregate underutilized capacity from multiple buildings to serve community needs',
    apiPath: 'aggregation',
    badge: 'core',
    columns: [
      { key: 'plan_name', label: 'Plan Name' },
      { key: 'region', label: 'Region' },
      { key: 'buildings_count', label: 'Buildings' },
      { key: 'total_aggregated_kw', label: 'Aggregated kW', format: 'number' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'plan_name', label: 'Plan Name', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'buildings_count', label: 'Buildings Count', type: 'number' },
      { key: 'total_aggregated_kw', label: 'Total Aggregated (kW)', type: 'number' },
      { key: 'target_community', label: 'Target Community', type: 'text' },
      { key: 'estimated_savings', label: 'Estimated Savings ($)', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'proposed', 'approved', 'active', 'completed'] },
    ],
    detailFields: [
      { key: 'plan_name', label: 'Plan Name' },
      { key: 'region', label: 'Region' },
      { key: 'buildings_count', label: 'Buildings' },
      { key: 'total_aggregated_kw', label: 'Aggregated (kW)' },
      { key: 'target_community', label: 'Target Community' },
      { key: 'estimated_savings', label: 'Estimated Savings' },
      { key: 'start_date', label: 'Start Date' },
      { key: 'end_date', label: 'End Date' },
      { key: 'status', label: 'Status' },
    ],
  },

  'grid-stability': {
    title: 'Grid Stability',
    icon: '📡',
    description: 'Real-time monitoring of grid stability metrics across all service regions',
    apiPath: 'grid-stability',
    badge: 'monitor',
    columns: [
      { key: 'region', label: 'Region' },
      { key: 'frequency_hz', label: 'Freq (Hz)' },
      { key: 'stability_index', label: 'Stability', format: 'number' },
      { key: 'risk_level', label: 'Risk', format: 'status' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'region', label: 'Region', type: 'text', required: true },
      { key: 'frequency_hz', label: 'Frequency (Hz)', type: 'number' },
      { key: 'voltage_kv', label: 'Voltage (kV)', type: 'number' },
      { key: 'load_mw', label: 'Load (MW)', type: 'number' },
      { key: 'generation_mw', label: 'Generation (MW)', type: 'number' },
      { key: 'renewable_pct', label: 'Renewable %', type: 'number' },
      { key: 'stability_index', label: 'Stability Index (0-100)', type: 'number' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'status', label: 'Status', type: 'select', options: ['normal', 'caution', 'warning', 'emergency'] },
    ],
    detailFields: [
      { key: 'region', label: 'Region' },
      { key: 'frequency_hz', label: 'Frequency (Hz)' },
      { key: 'voltage_kv', label: 'Voltage (kV)' },
      { key: 'load_mw', label: 'Load (MW)' },
      { key: 'generation_mw', label: 'Generation (MW)' },
      { key: 'renewable_pct', label: 'Renewable %' },
      { key: 'stability_index', label: 'Stability Index' },
      { key: 'risk_level', label: 'Risk Level' },
      { key: 'status', label: 'Status' },
    ],
  },

  'equity-scores': {
    title: 'Equity Scoring',
    icon: '⚖️',
    description: 'AI-powered social equity scoring for communities to prioritize energy redistribution',
    apiPath: 'equity-scores',
    badge: 'ai',
    columns: [
      { key: 'community_name', label: 'Community' },
      { key: 'region', label: 'Region' },
      { key: 'score', label: 'Score', format: 'number' },
      { key: 'affordability_score', label: 'Affordability', format: 'number' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'community_name', label: 'Community Name', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'score', label: 'Overall Score (0-100)', type: 'number' },
      { key: 'energy_access_score', label: 'Energy Access Score', type: 'number' },
      { key: 'affordability_score', label: 'Affordability Score', type: 'number' },
      { key: 'reliability_score', label: 'Reliability Score', type: 'number' },
      { key: 'environmental_score', label: 'Environmental Score', type: 'number' },
      { key: 'health_impact_score', label: 'Health Impact Score', type: 'number' },
      { key: 'assessment_date', label: 'Assessment Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'under_review', 'archived'] },
    ],
    detailFields: [
      { key: 'community_name', label: 'Community' },
      { key: 'region', label: 'Region' },
      { key: 'score', label: 'Overall Score' },
      { key: 'energy_access_score', label: 'Energy Access' },
      { key: 'affordability_score', label: 'Affordability' },
      { key: 'reliability_score', label: 'Reliability' },
      { key: 'environmental_score', label: 'Environmental' },
      { key: 'health_impact_score', label: 'Health Impact' },
      { key: 'assessment_date', label: 'Assessment Date' },
      { key: 'status', label: 'Status' },
    ],
  },

  redistribution: {
    title: 'Redistribution Plans',
    icon: '🔄',
    description: 'Plan and execute energy redistribution from surplus buildings to underserved communities',
    apiPath: 'redistribution',
    badge: 'core',
    columns: [
      { key: 'plan_name', label: 'Plan Name' },
      { key: 'target_community', label: 'Community' },
      { key: 'capacity_kw', label: 'Capacity kW', format: 'number' },
      { key: 'estimated_beneficiaries', label: 'Beneficiaries', format: 'number' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'plan_name', label: 'Plan Name', type: 'text', required: true },
      { key: 'source_buildings', label: 'Source Buildings', type: 'text' },
      { key: 'target_community', label: 'Target Community', type: 'text' },
      { key: 'capacity_kw', label: 'Capacity (kW)', type: 'number' },
      { key: 'estimated_beneficiaries', label: 'Estimated Beneficiaries', type: 'number' },
      { key: 'cost_estimate', label: 'Cost Estimate ($)', type: 'number' },
      { key: 'timeline_months', label: 'Timeline (months)', type: 'number' },
      { key: 'priority', label: 'Priority (1-5)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['proposed', 'approved', 'in_progress', 'completed'] },
    ],
    detailFields: [
      { key: 'plan_name', label: 'Plan Name' },
      { key: 'source_buildings', label: 'Source Buildings', fullWidth: true },
      { key: 'target_community', label: 'Target Community' },
      { key: 'capacity_kw', label: 'Capacity (kW)' },
      { key: 'estimated_beneficiaries', label: 'Beneficiaries' },
      { key: 'cost_estimate', label: 'Cost Estimate' },
      { key: 'timeline_months', label: 'Timeline (months)' },
      { key: 'priority', label: 'Priority' },
      { key: 'status', label: 'Status' },
    ],
  },

  'demand-response': {
    title: 'Demand Response',
    icon: '📉',
    description: 'Manage demand response programs to balance grid load and incentivize participation',
    apiPath: 'demand-response',
    badge: 'monitor',
    columns: [
      { key: 'program_name', label: 'Program' },
      { key: 'program_type', label: 'Type' },
      { key: 'enrolled_buildings', label: 'Enrolled' },
      { key: 'capacity_committed_kw', label: 'Committed kW', format: 'number' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'program_name', label: 'Program Name', type: 'text', required: true },
      { key: 'program_type', label: 'Type', type: 'select', options: ['Curtailment', 'Load Shifting', 'Emergency', 'Automated', 'Flexible', 'Storage'] },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'enrolled_buildings', label: 'Enrolled Buildings', type: 'number' },
      { key: 'capacity_committed_kw', label: 'Committed Capacity (kW)', type: 'number' },
      { key: 'incentive_rate', label: 'Incentive Rate ($/kWh)', type: 'number' },
      { key: 'season', label: 'Season', type: 'select', options: ['Summer', 'Winter', 'Year-round'] },
      { key: 'peak_hours', label: 'Peak Hours', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'enrolling', 'standby', 'pilot', 'completed'] },
    ],
    detailFields: [
      { key: 'program_name', label: 'Program Name' },
      { key: 'program_type', label: 'Type' },
      { key: 'region', label: 'Region' },
      { key: 'enrolled_buildings', label: 'Enrolled Buildings' },
      { key: 'capacity_committed_kw', label: 'Committed (kW)' },
      { key: 'incentive_rate', label: 'Incentive Rate' },
      { key: 'season', label: 'Season' },
      { key: 'peak_hours', label: 'Peak Hours' },
      { key: 'status', label: 'Status' },
    ],
  },

  'capacity-forecast': {
    title: 'AI Forecasting',
    icon: '🤖',
    description: 'AI-powered capacity forecasting for predicting energy supply and demand dynamics',
    apiPath: 'capacity-forecast',
    badge: 'ai',
    columns: [
      { key: 'region', label: 'Region' },
      { key: 'forecast_date', label: 'Forecast Date' },
      { key: 'predicted_surplus_mw', label: 'Surplus MW', format: 'number' },
      { key: 'confidence_pct', label: 'Confidence', format: 'percent' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'region', label: 'Region', type: 'text', required: true },
      { key: 'forecast_date', label: 'Forecast Date', type: 'date' },
      { key: 'predicted_demand_mw', label: 'Predicted Demand (MW)', type: 'number' },
      { key: 'predicted_supply_mw', label: 'Predicted Supply (MW)', type: 'number' },
      { key: 'predicted_surplus_mw', label: 'Predicted Surplus (MW)', type: 'number' },
      { key: 'confidence_pct', label: 'Confidence %', type: 'number' },
      { key: 'weather_factor', label: 'Weather Factor', type: 'text' },
      { key: 'season', label: 'Season', type: 'select', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
      { key: 'model_version', label: 'Model Version', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'validated', 'warning', 'critical'] },
    ],
    detailFields: [
      { key: 'region', label: 'Region' },
      { key: 'forecast_date', label: 'Forecast Date' },
      { key: 'predicted_demand_mw', label: 'Demand (MW)' },
      { key: 'predicted_supply_mw', label: 'Supply (MW)' },
      { key: 'predicted_surplus_mw', label: 'Surplus (MW)' },
      { key: 'confidence_pct', label: 'Confidence %' },
      { key: 'weather_factor', label: 'Weather Factor' },
      { key: 'season', label: 'Season' },
      { key: 'model_version', label: 'Model Version' },
      { key: 'status', label: 'Status' },
    ],
  },

  'impact-reports': {
    title: 'Impact Reports',
    icon: '📈',
    description: 'Track and measure community impact of energy redistribution programs',
    apiPath: 'impact-reports',
    badge: 'core',
    columns: [
      { key: 'report_title', label: 'Report' },
      { key: 'community_name', label: 'Community' },
      { key: 'households_served', label: 'Households', format: 'number' },
      { key: 'cost_savings', label: 'Savings $', format: 'currency' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'report_title', label: 'Report Title', type: 'text', required: true },
      { key: 'community_name', label: 'Community Name', type: 'text' },
      { key: 'report_date', label: 'Report Date', type: 'date' },
      { key: 'households_served', label: 'Households Served', type: 'number' },
      { key: 'energy_saved_kwh', label: 'Energy Saved (kWh)', type: 'number' },
      { key: 'cost_savings', label: 'Cost Savings ($)', type: 'number' },
      { key: 'carbon_reduction_tons', label: 'Carbon Reduction (tons)', type: 'number' },
      { key: 'jobs_created', label: 'Jobs Created', type: 'number' },
      { key: 'satisfaction_score', label: 'Satisfaction (1-10)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived'] },
    ],
    detailFields: [
      { key: 'report_title', label: 'Title', fullWidth: true },
      { key: 'community_name', label: 'Community' },
      { key: 'report_date', label: 'Date' },
      { key: 'households_served', label: 'Households' },
      { key: 'energy_saved_kwh', label: 'Energy Saved (kWh)' },
      { key: 'cost_savings', label: 'Cost Savings' },
      { key: 'carbon_reduction_tons', label: 'Carbon Reduction' },
      { key: 'jobs_created', label: 'Jobs Created' },
      { key: 'satisfaction_score', label: 'Satisfaction' },
      { key: 'status', label: 'Status' },
    ],
  },

  'energy-savings': {
    title: 'Energy Savings',
    icon: '💰',
    description: 'Track and analyze energy savings across buildings with verification status',
    apiPath: 'energy-savings',
    badge: 'monitor',
    columns: [
      { key: 'building_name', label: 'Building' },
      { key: 'period', label: 'Period' },
      { key: 'saved_kwh', label: 'Saved kWh', format: 'number' },
      { key: 'savings_pct', label: 'Savings %', format: 'percent' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'building_name', label: 'Building Name', type: 'text', required: true },
      { key: 'period', label: 'Period', type: 'text' },
      { key: 'baseline_kwh', label: 'Baseline (kWh)', type: 'number' },
      { key: 'actual_kwh', label: 'Actual (kWh)', type: 'number' },
      { key: 'saved_kwh', label: 'Saved (kWh)', type: 'number' },
      { key: 'savings_pct', label: 'Savings %', type: 'number' },
      { key: 'cost_saved', label: 'Cost Saved ($)', type: 'number' },
      { key: 'method', label: 'Method', type: 'text' },
      { key: 'verified', label: 'Verified', type: 'select', options: ['true', 'false'] },
      { key: 'status', label: 'Status', type: 'select', options: ['recorded', 'pending', 'verified'] },
    ],
    detailFields: [
      { key: 'building_name', label: 'Building' },
      { key: 'period', label: 'Period' },
      { key: 'baseline_kwh', label: 'Baseline (kWh)' },
      { key: 'actual_kwh', label: 'Actual (kWh)' },
      { key: 'saved_kwh', label: 'Saved (kWh)' },
      { key: 'savings_pct', label: 'Savings %' },
      { key: 'cost_saved', label: 'Cost Saved' },
      { key: 'method', label: 'Method' },
      { key: 'verified', label: 'Verified' },
      { key: 'status', label: 'Status' },
    ],
  },

  alerts: {
    title: 'Alert Management',
    icon: '🚨',
    description: 'Monitor and respond to grid alerts, equipment warnings, and system notifications',
    apiPath: 'alerts',
    badge: 'monitor',
    columns: [
      { key: 'title', label: 'Alert' },
      { key: 'alert_type', label: 'Type' },
      { key: 'severity', label: 'Severity', format: 'status' },
      { key: 'region', label: 'Region' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'alert_type', label: 'Alert Type', type: 'select', options: ['Grid Overload', 'Frequency', 'Voltage', 'Curtailment', 'Equipment', 'Demand', 'Data Quality', 'Outage', 'Communication', 'Storage', 'Demand Response', 'Security', 'Weather', 'Compliance'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'acknowledged', label: 'Acknowledged', type: 'select', options: ['true', 'false'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'resolved', 'dismissed'] },
    ],
    detailFields: [
      { key: 'title', label: 'Title', fullWidth: true },
      { key: 'alert_type', label: 'Type' },
      { key: 'severity', label: 'Severity' },
      { key: 'source', label: 'Source' },
      { key: 'region', label: 'Region' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'acknowledged', label: 'Acknowledged' },
      { key: 'status', label: 'Status' },
    ],
  },

  compliance: {
    title: 'Compliance & Reporting',
    icon: '📋',
    description: 'Track regulatory compliance, audits, and reporting requirements across jurisdictions',
    apiPath: 'compliance',
    badge: 'core',
    columns: [
      { key: 'report_name', label: 'Report' },
      { key: 'regulation', label: 'Regulation' },
      { key: 'compliance_score', label: 'Score', format: 'number' },
      { key: 'due_date', label: 'Due Date' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'report_name', label: 'Report Name', type: 'text', required: true },
      { key: 'regulation', label: 'Regulation', type: 'text' },
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'select', options: ['Federal', 'California', 'Local'] },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'submitted_date', label: 'Submitted Date', type: 'date' },
      { key: 'compliance_score', label: 'Compliance Score (%)', type: 'number' },
      { key: 'findings', label: 'Findings', type: 'textarea' },
      { key: 'corrective_actions', label: 'Corrective Actions', type: 'textarea' },
      { key: 'auditor', label: 'Auditor', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'submitted', 'approved'] },
    ],
    detailFields: [
      { key: 'report_name', label: 'Report Name', fullWidth: true },
      { key: 'regulation', label: 'Regulation' },
      { key: 'jurisdiction', label: 'Jurisdiction' },
      { key: 'due_date', label: 'Due Date' },
      { key: 'submitted_date', label: 'Submitted Date' },
      { key: 'compliance_score', label: 'Score (%)' },
      { key: 'findings', label: 'Findings', fullWidth: true },
      { key: 'corrective_actions', label: 'Corrective Actions', fullWidth: true },
      { key: 'auditor', label: 'Auditor' },
      { key: 'status', label: 'Status' },
    ],
  },

  partners: {
    title: 'Partner Network',
    icon: '🤝',
    description: 'Manage partnerships with technology providers, contractors, and community organizations',
    apiPath: 'partners',
    badge: 'core',
    columns: [
      { key: 'partner_name', label: 'Partner' },
      { key: 'partner_type', label: 'Type' },
      { key: 'region', label: 'Region' },
      { key: 'buildings_managed', label: 'Buildings' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'partner_name', label: 'Partner Name', type: 'text', required: true },
      { key: 'partner_type', label: 'Type', type: 'select', options: ['Technology', 'Consulting', 'Non-Profit', 'Contractor', 'Financial', 'Utility', 'Engineering', 'Cooperative'] },
      { key: 'contact_person', label: 'Contact Person', type: 'text' },
      { key: 'contact_email', label: 'Contact Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'region', label: 'Region', type: 'text' },
      { key: 'services_offered', label: 'Services Offered', type: 'textarea' },
      { key: 'buildings_managed', label: 'Buildings Managed', type: 'number' },
      { key: 'partnership_since', label: 'Partnership Since', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'pending'] },
    ],
    detailFields: [
      { key: 'partner_name', label: 'Partner Name' },
      { key: 'partner_type', label: 'Type' },
      { key: 'contact_person', label: 'Contact' },
      { key: 'contact_email', label: 'Email' },
      { key: 'phone', label: 'Phone' },
      { key: 'region', label: 'Region' },
      { key: 'services_offered', label: 'Services', fullWidth: true },
      { key: 'buildings_managed', label: 'Buildings Managed' },
      { key: 'partnership_since', label: 'Since' },
      { key: 'status', label: 'Status' },
    ],
  },
};
